TG Specification
================
:Author:    Claudio Klingler
:Email:     ck@realtime-projects.com
:Date:      2011-07-23

Author: {author}

Creation Date: {date}

== License

Copyright (c) 2011, realtime projects, claudio klingler

All rights reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

- Redistributions of source code must retain the above copyright notice, this list
  of conditions and the following disclaimer.
- Redistributions in binary form must reproduce the above copyright notice, this list
  of conditions and the following disclaimer in the documentation and/or other
  materials provided with the distribution.
- Neither the name of the - realtime projects - nor the names of its contributors may be used
  to endorse or promote products derived from this software without specific prior written
  permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

== Abstract

+tg+ is a simple and sophisticated tool for template generation. +tg+ creates templates from blueprints you
prepared before or manage on a central place.

== About this document

This document contains the - for the moment - the full official project documentation. 

The 'Project Goals' inform you about the main objectives behind this project. Further on, the
'Basic Concept' chapter describes, how +tg+ in basic works in order to give you an overview,
what +tg+ does. Further on, the 'TG Definitions' chapter, shortly named "TGDEF", contains the
official specification of +tg+ and its properties. The last chapter, 'This document's templates'
still contain some asciidoc templates for later use in this document. This chapter is intended to
be removed in later versions.

== Conventions

- 'Official Terms' are written in capital letters, like 'Official Terms'. Their definition is
  either located in the 'TG Definitions' section or in this 'Conventions' section. Furthermore,
  a Chapter in this document may represent an 'Official Term', too.
- 'TBD' signals a place where there is still work to do.

== Project Goals

This project aims to:

- Simplify the daily developer's work by offering a smart command line tool that helps him to generate
  his templates of his source code files.
- Allow a central management of the blueprints, so that development teams are able to use one single source
  for their blueprints, what ease up work and improves quality standars.
- Avoid common copy-and-paste errors like "oops, i did not update the author tag in the source file".

== Resources

The official project homepage is located at github under https://github.com/realtimeprojects/tg. The
git repository contains it's documentation in the 'doc/' subdirectory. It's 'examples/template' directory
contain some basic examples of templates. When running the tests, a 'test/output' directory is created,
containing templates generated by +tg+ during it's test run. _tg_ itself is a perl script, the real +tg+ source.
The '.tg_completion.sh' enables bash completion support. The 'tgtest.sh' bash script represents the automated
test bench for +tg+.

== Basic concept

TBD - sorry

== TG Definitions (TGDEF)

=== Template Directory Reference Specification (TDRS)

A 'Template Directory Reference Specification' specifies a location where +tg+ searches for
'Template Containers'. The reference specification may either be

- a absolute or relative path specification like _../mymksourcetemplates_ or _/opt/etc/mymksourcetemplates_, or
- a http-URL reference like http://tg.realtime-projects.com/templates. (Link does not work yet, sorry!).

NOTE:   You may place your templates on a simple public http webserver to make them accessable for
        your team. All your members have to do is to add the http-URL to their 'Template Path'

STATUS: Specification

== Template Container (TCNT)

A 'Template Container' is a directory that holds any number of 'Blueprint Files'. +tg+ will create a template
for every Blueprint File within a Template Container.

STATUS: Tested

=== Blueprint File

A 'Blueprint File' is the blueprint from which +tg+ creates your template. A blueprint file is a text file.
If the Blueprint File contains 'TG Keywords', +tg+ replaces every TG Keyword using the 'Blueprint Replacement Rule'.

If the filename of a Blueprint File itself also consists of TG Keywords, +tg+ will make the 'Blueprint Replacement Rule' also on the
Filename.

[NOTE]
This allows to dynamically create the target file names depending on the 'Runtime Settings', e.g. a Blueprint File named
_@Target@.cpp_ will generate a Template File named _Main.cpp_, if it is called like: +tg -t cpp create Main+

=== TG Keyword

+tg+ replaces each 'TG Keyword' in a 'Blueprint File' using the 'Blueprint Replacement Rule'. A TG Keyword is surrounded by
the +@+ sign, like +@Target@+. See Blueprint Replacement Rule for the available TG Keywords and how they are replaced.

=== Blueprint Replacement Rule

The Blueprint Replacement Rule defines the logic how +tg+ replaces the 'TG Keywords'
in the 'Blueprint File'. The replacement may be any Runtime Setting, e.g. the name of
the target the user specifies by the +tg create+ command, like +tg create TargetName+.

Here is the list of the replacements:

*Target*

+tg+ replaces the @Target@ pattern by the Target Name that the user specifies on the
command line.

*IsoDate*

+tg+ the @IsoDate@ pattern is replaced by the current date (local time), the date of
template generation. The date is printed out in ISO-8601 format, like: '2011-07-23'.

*Year*

+tg+ replaces the @Year@ pattern with the current year on template generation.

NOTE: This may be used for +(c) @Year@ <Company Name>+ notations in the Blueprint File.

*User*

+tg+ replaces the @User@ pattern by the User Name. See the rule how the User Name is
determined in the 'User Name' definition. At leased, +tg+ uses the environment variable
+LOGNAME+.

=== Template Generation

+tg+ generates for each Blueprint File in a Template Container a Template File by using
the Replacement Rules. Existing files are skipped unless the user forces overwriting, e.g.
by using the command line switch '-f', like +tg -f -t cpp create Main+. +tg+ prints out a
warning for every skipped file.

=== Exit Code

+tg+ returns 0 when it generated the templates successfully, even when it skips the
generation due to existing template files.

If +tg+ detects an error during execution, +tg+ terminates with a exit status of 1.

=== User Name
TBD

== This Document's templates

==== Level3

===== Level4
.Optional Titel
NOTE: This is a note (delte line for simple title)

.Optional Titel
TIP: This is a tip

.Optional Titel
Warning: Be careful!

 Literal paragraph

[source, c++]
----
for (int ii = 0; ii < 100; ii++)
{
    printf("%d\n", ii);
} 
----
